version: "2"

linters:
  default: none
  enable:
    # 基础检查
    - govet
    - staticcheck
    - errcheck
    - unused

    # 风格
    - revive
    - unconvert

    # 安全
    - gosec

    # 并发
    - bodyclose
    - noctx

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: aip
        linters:
          - gocyclo
          - errcheck
          - staticcheck
          - dupl
          - gosec
          - revive

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    paths:
      - "basic/aip"